ALTER view [dbo].[bulk_events] 
as 
SELECT [evb1] 
      ,[evb2] 
      ,[evb3] 
      ,[evb4] 
      ,[evb5] 
      ,[evb6] 
      ,[evb7] 
      ,[evb8] 
      ,[evb9] 
      ,[evb10] 
      ,[pal1] 
      ,[pal2] 
      ,[date] 
      ,[timezonebias] 
	  ,[mpal1]
	  ,[mpal2]
  FROM [dbo].[device_data] 
  where date = '2016-12-01' 